#!/usr/bin/env bash
# Script to count to 100 and print fizz, buzz and fizzbuzz instead of some numbers
i=1
while (( "$i" <= 100 ))
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [[ $((i % 3)) -eq 0 ]]
	then
		echo "Fizz"
	elif [[ $((i % 5)) -eq 0 ]]
	then
		echo "Buzz"
	#elif [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	#then
	#	echo "FizzBuzz"
	else
		echo "$i"
	fi
	i=$((i + 1))
done
