#!/usr/bin/env bash
# Script to count from 0-9 and print some statement incase of number on the way
i=0
while [ "$i" -le 9 ]
do
	if (("$i" == 3))
	then
		echo "bad luck"
	elif (("$i" == 7))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i + 1))
done
