#!/usr/bin/env bash
i=0
while (( "$i" <= 20 ))
do
	case "$i" in
		4)
			echo "$i"			
			echo "bad luck from China"
		;;
		9)
			echo "$i"
			echo "bad luck from Japa"
		;;
		17)
			echo "$i"
			echo "bad luck from Italy"
		;;
		*)
			echo "$i"
	esac
	i=$((i + 1))
done
