#!/usr/bin/env bash
# Script to get the content of the current directory and extract a file with name
fileName=$(ls | cut -d'-' -f1 | grep school)
if [ -e "$fileName" ]
then
	echo "school file exists"
	if [ -s "$fileName" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$fileName" ]
	then
		echo "school file is a regular file"
	fi
else
	echo "school file does not exist"
fi
